// This file was autogenerated by calcdeps.py
goog.addDependency("../../../workspace2011/RoseGrid/experimental/exp_popup_window.js", ['exprosegrid.PopupWindow'], ['goog.dom', 'goog.events', 'goog.ui.Control', 'goog.ui.Dialog']);
