// This file was autogenerated by ../../../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../closure-templates/javascript/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency('../../../workspace2012/Rose-Hulman_WeeklySchedule_ChromeExtension/build/templates/popup_window.soy.js', ['rosegrid.templates'], ['soy', 'soy.StringBuilder']);
goog.addDependency('../../../workspace2012/Rose-Hulman_WeeklySchedule_ChromeExtension/js/cell_control.js', ['rosegrid.ui.CellControl'], ['goog.dom', 'goog.events', 'goog.string', 'goog.ui.Control', 'rosegrid.model.Cell']);
goog.addDependency('../../../workspace2012/Rose-Hulman_WeeklySchedule_ChromeExtension/js/model/cell.js', ['rosegrid.model.Cell'], ['goog.string']);
goog.addDependency('../../../workspace2012/Rose-Hulman_WeeklySchedule_ChromeExtension/js/model/course.js', ['rosegrid.model.Course'], []);
goog.addDependency('../../../workspace2012/Rose-Hulman_WeeklySchedule_ChromeExtension/js/model/day.js', ['rosegrid.Period', 'rosegrid.Weekday', 'rosegrid.model.Day'], ['goog.array', 'rosegrid.model.Cell']);
goog.addDependency('../../../workspace2012/Rose-Hulman_WeeklySchedule_ChromeExtension/js/model/week.js', ['rosegrid.CellIndex', 'rosegrid.model.Week'], ['goog.array', 'rosegrid.Period', 'rosegrid.Weekday', 'rosegrid.model.Cell', 'rosegrid.model.Day']);
goog.addDependency('../../../workspace2012/Rose-Hulman_WeeklySchedule_ChromeExtension/js/popup_window.js', ['rosegrid.PopupWindow'], ['goog.debug', 'goog.debug.Console', 'goog.debug.Logger', 'goog.dom', 'goog.events', 'goog.soy', 'goog.ui.Dialog', 'rosegrid.model.Week', 'rosegrid.templates', 'rosegrid.ui.CellControl']);
